import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const dangsik = localFont({
  src: "../fonts/DANGSIKDEMO-BF673ef8f770e37.otf",
  variable: "--font-dangsik",
  weight: "100 900",
});
const pocahontas = localFont({
  src: "../fonts/Pocahontas.ttf",
  variable: "--font-pocahontas",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dangsik.variable} ${pocahontas.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
